version: "3.7"

services:
  revcord:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /volume1/configs/revcord/revcord.sqlite:/app/revcord.sqlite:rw
      - /volume1/configs/revcord/.env:/app/.env
    restart: unless-stopped
